App/ProjectBranchSelector/Controllers/FormulaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using ProjectBranchSelector.Models;
using ProjectBranchSelector.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace ProjectBranchSelector.Controllers
{
    public class FormulaController : CommonControllerBase
    {       
        public FormulaController(IServiceProvider serviceProvider): base(serviceProvider)
        {
            _logger = serviceProvider.GetRequiredService<ILogger<FormulaController>>();            
        }

        // GET: FormulaController
        public ActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Filtered(string name = null, int page = 0, int size = 10, string sort = null)
        {
            try
            {
                var result = await dataService.GetFormulas(new FormulaFilter(name, page, size, sort, true), cancellationToken);
                var pages = (result.Item1 % size == 0) ? (result.Item1 / size) : (result.Item1 / size) + 1;
                if (Response != null) Response.Headers.Add("x-pages", pages.ToString());
                return PartialView(result.Item2);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Method GetFormulas exception: {ex.Message} + ST: {ex.StackTrace}");
                return RedirectToAction("Error", $"Method GetFormulas exception: {ex.Message} + ST: {ex.StackTrace}");
            }
        }

        public ActionResult ListSelect()
        {
            return PartialView();
        }

        public async Task<IActionResult> ListSelectFiltered(string name = null, int page = 0, int size = 10, string sort = null)
        {
            try
            {
                var result = await dataService.GetFormulas(new FormulaFilter(name, page, size, sort, true), cancellationToken);
                Response.Headers.Add("x-pages", result.Item1.ToString());
                return PartialView(result.Item2);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Method GetFormulas exception: {ex.Message} + ST: {ex.StackTrace}");
                return RedirectToAction("Error", $"Method GetFormulas exception: {ex.Message} + ST: {ex.StackTrace}");
            }
        }

        // GET: FormulaController/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            try
            {
                var model = await dataService.GetFormula(id, cancellationToken);
                return View(model);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Method GetFormula exception: {ex.Message} + ST: {ex.StackTrace}");
                return RedirectToAction("Error", $"Method GetFormula exception: {ex.Message} + ST: {ex.StackTrace}");
            }
        }

        // GET: FormulaController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FormulaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FormulaController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: FormulaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FormulaController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: FormulaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

App/ProjectBranchSelector/Controllers/TreeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using ProjectBranchSelector.Models;
using ProjectBranchSelector.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace ProjectBranchSelector.Controllers
{
    public class TreeController : CommonControllerBase
    {       
        public TreeController(IServiceProvider serviceProvider): base(serviceProvider)
        {
            _logger = serviceProvider.GetRequiredService<ILogger<TreeController>>();            
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> TreeFiltered(string name = null, int page = 0, int size = 10, string sort = null)
        {
            try
            {
                var result = await dataService.GetTrees(new TreeFilter(name, page, size, sort, true), cancellationToken);                
                var pages = (result.Item1 % size == 0) ? (result.Item1 / size) : (result.Item1 / size) + 1;
                if (Response != null) Response.Headers.Add("x-pages", pages.ToString());
                return PartialView(result.Item2);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Method GetTrees exception: {ex.Message} + ST: {ex.StackTrace}");
                return RedirectToAction("Error", $"Method GetTrees exception: {ex.Message} + ST: {ex.StackTrace}");
            }
        }

        public async Task<IActionResult> TreeCount(string name = null, int page = 0, int size = 10, string sort = null)
        {
            try
            {
                return Ok(await dataService.GetTreesCount(new TreeFilter(name, page, size, sort, true), cancellationToken));
            }
            catch (Exception ex)
            {
                _logger.LogError($"Method GetTrees exception: {ex.Message} + ST: {ex.StackTrace}");
                return RedirectToAction("Error", $"Method GetTrees exception: {ex.Message} + ST: {ex.StackTrace}");
            }
        }

        [HttpGet]
        public async Task<JsonResult> CheckName(string name)
        {
            bool result = false;
            if (!string.IsNullOrEmpty(name))
            {
                var check = await dataService.GetTrees(new TreeFilter(name, 0, 10, null), cancellationToken);
                result = !check.Item2.Any();
            }
            return Json(result);
        }

        [HttpGet]
        public async Task<JsonResult> CheckFormulaId(Guid id)
        {
            var check = await dataService.GetFormula(id, cancellationToken);
            var result = check!=null;
            return Json(result);
        }

        public async Task<IActionResult> ListSelect(string name = null, int page = 0, int size = 10, string sort = null)
        {
            try
            {
                return PartialView(await dataService.GetTrees(new TreeFilter(name, page, size, sort, true), cancellationToken));
            }
            catch (Exception ex)
            {
                _logger.LogError($"Method GetTrees exception: {ex.Message} + ST: {ex.StackTrace}");
                return RedirectToAction("Error", $"Method GetTrees exception: {ex.Message} + ST: {ex.StackTrace}");
            }
        }

        // GET: Project/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            try
            {
                var model = await dataService.GetTree(id, cancellationToken);
                return View(model);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Method GetTree exception: {ex.Message} + ST: {ex.StackTrace}");
                return RedirectToAction("Error", $"Method GetTree exception: {ex.Message} + ST: {ex.StackTrace}");
            }
        }

        // GET: Project/Create
        public async Task<ActionResult> Create()
        {
            var formula = await dataService.GetDefaultFormula(cancellationToken);
            TreeModel item = new TreeModel()
            { 
               FormulaId = formula.Id,
               Formula = formula.Name
            };
            return View(item);
        }

        // POST: Project/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TreeModel item)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TreeModel model = await dataService.AddTree(new TreeCreator()
                    { 
                      Description = item.Description,
                      FormulaId = item.FormulaId,
                      Name = item.Name
                    }, cancellationToken);
                    return RedirectToAction(nameof(Details), new { id = model.Id });
                }
                else
                {
                    var formula = await dataService.GetDefaultFormula(cancellationToken);
                    return View(item);
                }
            }
            catch(Exception ex)
            {
                return RedirectToAction("Error", $"Method AddTree exception: {ex.Message} + ST: {ex.StackTrace}");
            }
        }
                
        // GET: Project/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            try
            {
                TreeModel model = await dataService.GetTree(id, cancellationToken);
                return View(model);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", $"Method GetTree exception: {ex.Message} + ST: {ex.StackTrace}");
            }
        }

        // POST: Project/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(TreeUpdater item)
        {
            try
            {
                TreeModel model = await dataService.UpdateTree(item, cancellationToken);                
                return RedirectToAction("Details", new { id = item.Id});
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", $"Method GetTree exception: {ex.Message} + ST: {ex.StackTrace}");
            }
        }

        // GET: Project/Delete/5
        public async Task<IActionResult> Delete(Guid id)
        {
            try
            {
                TreeModel model = await dataService.GetTree(id, cancellationToken);
                return View(model);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", $"Method GetTree exception: {ex.Message} + ST: {ex.StackTrace}");
            }            
        }

        // POST: Project/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Guid id, TreeModel item)
        {
            try
            {
                TreeModel model = await dataService.DeleteTree(item.Id, cancellationToken);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", $"Method GetTree exception: {ex.Message} + ST: {ex.StackTrace}");
            }
        }
    }
}

App/ProjectBranchSelector/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Выбор элемента дерева: @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="dropdown col-sm-1">
                    <button class="btn btn-secondary" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M2.5 11.5A.5.5 0 0 1 3 11h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 7h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 3h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z" />
                        </svg>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">Домой</a>
                        <a class="dropdown-item" asp-area="" asp-controller="Tree" asp-action="Index">Деревья</a>
                        <a class="dropdown-item" asp-area="" asp-controller="Formula" asp-action="Index">Формулы</a>
                    </div>
                </div>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Выбор элемента дерева</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Домой</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Пользовательское соглашение</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Выбор элемента дерева - <a asp-area="" asp-controller="Home" asp-action="Privacy">Пользовательское соглашение</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>