App/ProjectBranchSelector/Controllers/TreeItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using ProjectBranchSelector.Models;
using ProjectBranchSelector.Service;

namespace ProjectBranchSelector.Controllers
{
    public class TreeItemController : Controller
    {
        private readonly ILogger<TreeController> _logger;
        private readonly IDataService dataService;
        private readonly CancellationToken cancellationToken;
        private readonly CancellationTokenSource tokenSource;

        public TreeItemController(IServiceProvider serviceProvider)
        {
            _logger = serviceProvider.GetRequiredService<ILogger<TreeController>>();
            dataService = serviceProvider.GetRequiredService<IDataService>();
            tokenSource = new CancellationTokenSource();
            cancellationToken = tokenSource.Token;
        }

        // GET: Node
        public async Task<IActionResult> Index(Guid treeId)
        {
            try
            {
                return View(await dataService.GetTreeItems(treeId, cancellationToken));
            }
            catch (Exception ex)
            {
                _logger.LogError($"Method GetTreeItems exception: {ex.Message} + ST: {ex.StackTrace}");
                return RedirectToAction("Error", $"Method GetTreeItems exception: {ex.Message} + ST: {ex.StackTrace}");
            }
        }

        public async Task<IActionResult> ListSelect(Guid treeId)
        {
            try
            {
                return View(await dataService.GetTreeItems(treeId, cancellationToken));
            }
            catch (Exception ex)
            {
                _logger.LogError($"Method GetTreeItems exception: {ex.Message} + ST: {ex.StackTrace}");
                return RedirectToAction("Error", $"Method GetTreeItems exception: {ex.Message} + ST: {ex.StackTrace}");
            }
        }

        // GET: Node/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            try
            {
                return View(await dataService.GetTreeItem(id, cancellationToken));
            }
            catch (Exception ex)
            {
                _logger.LogError($"Method GetTreeItems exception: {ex.Message} + ST: {ex.StackTrace}");
                return RedirectToAction("Error", $"Method GetTreeItems exception: {ex.Message} + ST: {ex.StackTrace}");
            }            
        }

        // GET: Node/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Node/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(TreeItemCreator item)
        {
            try
            {
                TreeItemModel model = await dataService.AddTreeItem(item, cancellationToken);
                return RedirectToAction(nameof(Details), new { id = model.Id });
            }
            catch (Exception ex)
            {
                _logger.LogError($"Method AddTreeItem exception: {ex.Message} + ST: {ex.StackTrace}");
                return RedirectToAction("Error", $"Method AddTreeItem exception: {ex.Message} + ST: {ex.StackTrace}");
            }
        }

        // GET: Node/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            try
            {
                var model = await dataService.GetTreeItem(id, cancellationToken);
                return View(model);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", $"Method GetTreeItem exception: {ex.Message} + ST: {ex.StackTrace}");
            }
        }

        // POST: Node/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(TreeItemUpdater item)
        {
            try
            {
                var model = await dataService.UpdateTreeItem(item, cancellationToken);
                return RedirectToAction("Details", new { id = item.Id });
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", $"Method UpdateTreeItem exception: {ex.Message} + ST: {ex.StackTrace}");
            }
        }

        // GET: Node/Delete/5
        public async Task<IActionResult> Delete(Guid id)
        {
            try
            {
                var model = await dataService.GetTreeItem(id, cancellationToken);
                return View(model);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", $"Method GetTreeItem exception: {ex.Message} + ST: {ex.StackTrace}");
            }
        }

        // POST: Node/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Guid id, TreeItemModel item)
        {
            try
            {
                var model = await dataService.DeleteTreeItem(item.Id, cancellationToken);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", $"Method DeleteTreeItem exception: {ex.Message} + ST: {ex.StackTrace}");
            }
        }

        [HttpGet]
        public async Task<JsonResult> CheckName(string name, Guid treeId, Guid? parentId)
        {
            var check = (await dataService.GetTreeItems(treeId, cancellationToken)).Item2
                .Where(s=>s.ParentId == parentId && s.Name == name);
            var result = !check.Any();
            return Json(result);
        }

        [HttpGet]
        public async Task<JsonResult> CheckTreeId(string name, Guid treeId, Guid? parentId)
        {
            var check = await dataService.GetTree(treeId, cancellationToken);
            var result = check != null;
            return Json(result);
        }

        [HttpGet]
        public async Task<JsonResult> CheckParentId(string name, Guid treeId, Guid? parentId)
        {
            if(parentId == null)
                return Json(true);

            var check = (await dataService.GetTreeItems(treeId, cancellationToken)).Item2
                .Where(s => s.Id == parentId);
            var result = check.Any();
            return Json(result);
        }

        [HttpGet]
        public async Task<JsonResult> CheckWeight(int weight, Guid treeId, Guid? parentId)
        {
            var check = weight > 0;
            return Json(check);
        }
    }
}

App/ProjectBranchSelector/Views/TreeItem/SelectCategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ProjectBranchSelector.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectBranchSelector.Views.TreeItem
{
    public class SelectCategoriesViewComponent : ViewComponent
    {
        public SelectCategoriesViewComponent()
        {
            
        }

        public async Task<IViewComponentResult> InvokeAsync(List<TreeItemModel> list, Guid parent)
        {            
            return await Task.Run(()=> View(list.Where(s => s.ParentId == parent)));
        }        
    }
}

App/ProjectBranchSelector/Views/TreeItem/Create.cshtml
@using ProjectBranchSelector.Models;
@model TreeItemModel

@{
    ViewData["Title"] = "Добавить";
}


<h4>@ViewData["Title"]</h4>
<hr />
<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TreeId" class="form-control" />
            <input type="hidden" asp-for="ParentId" class="form-control" id="parent_id" />
            <div class="form-group">
                <label>Родитель</label>
                <input id="parent" disabled class="form-control" />
                <span asp-validation-for="ParentId" class="text-danger" id="parent"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Weight" class="control-label"></label>
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AddFields" class="control-label"></label>
                <input asp-for="AddFields" class="form-control" />
                <span asp-validation-for="AddFields" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Выбрать родителя", "ListSelect", "TreeItem",
        new { id = Model.TreeId },
        new { @class = "btn btn-dark", @id = "parent_select" })
    @Html.ActionLink("Вернуться", "List")
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">

        function setParent(parent_id, parent) {
            $("#parent_id").text(parent_id);
            $("#parent").text(parent);
         }

            $(function () {
                $.ajaxSetup({ cache: false });
                $("#parent_select").click(function (e) {
                    e.preventDefault();
                    $.get(this.href, function (data) {
                        $('#dialogContent').html(data);
                        $('#modDialog').modal('show');
                    });
                });
            })
    </script>
}

App/ProjectBranchSelector/Views/TreeItem/Delete.cshtml
@model ProjectBranchSelector.Models.TreeItemModel

@{
    ViewData["Title"] = "Удаление элемента дерева";
}

<h1>Delete</h1>

<h3>Вы действительно хотите удалить данный эелемент?</h3>
<div>
    <h4>@ViewData["Title"]</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TreeId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TreeId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ParentId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ParentId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsLeaf)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsLeaf)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AddFields)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AddFields)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Weight)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Weight)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SelectCount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SelectCount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Parent)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Parent)
        </dd>        
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

App/ProjectBranchSelector/Views/TreeItem/Details.cshtml
@using ProjectBranchSelector.Models;
@model TreeItemModel

@{
    ViewData["Title"] = "Элемент дерева";    
}

<h1>@ViewData["Title"]</h1>

<div>
    <h4>NodeModel</h4>
    <hr />
    @Html.HiddenFor(model => model.Id)
<dl class="row">
    <dt class="col-sm-2">
        Наименование
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Name)
    </dd>
    <dt class="col-sm-2">
        Описание
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Description)
    </dd>
    <dt class="col-sm-2">
        Дерево
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Tree.Name)
    </dd>
    <dt class="col-sm-2">
        Родитель
    </dt>
    <dd class="col-sm-10">
        @if (Model.Parent != null)
        {
            @Html.DisplayFor(model => model.Parent.Name)
        }
    </dd>
</dl>
</div>
<div>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Вернуться", "Index")
</div>

App/ProjectBranchSelector/Views/TreeItem/Edit.cshtml
@using ProjectBranchSelector.Models;
@model TreeItemModel

@{
    ViewData["Title"] = "Edit";    
}

<h4>@ViewData["Title"]</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TreeId" class="form-control" />
            <input type="hidden" asp-for="ParentId" class="form-control" id="parent_id" />
            <input type="hidden" asp-for="Id" class="form-control" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tree" class="control-label"></label>
                <input asp-for="Tree" disabled class="form-control" />
                <span asp-validation-for="TreeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Parent" class="control-label"></label>
                <input asp-for="Parent" disabled class="form-control" id="parent" />
                <span asp-validation-for="ParentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Weight" class="control-label"></label>
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AddFields" class="control-label"></label>
                <input asp-for="AddFields" class="form-control" />
                <span asp-validation-for="AddFields" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Выбрать родителя", "ListSelect", "TreeItem",
        new { id = Model.TreeId },
        new { @class = "btn btn-dark", @id = "parent_select" })
    @Html.ActionLink("Вернуться", "List")
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">

            function setParent(parent_id, parent) {
                $("#parent_id").text(parent_id);
                $("#parent").text(parent);
             }

                $(function () {
                    $.ajaxSetup({ cache: false });
                    $("#parent_select").click(function (e) {
                        e.preventDefault();
                        $.get(this.href, function (data) {
                            $('#dialogContent').html(data);
                            $('#modDialog').modal('show');
                        });
                    });
                })
    </script>
}

App/ProjectBranchSelector/Views/TreeItem/History.cshtml
@using ProjectBranchSelector.Models;
@model IEnumerable<TreeItemHistoryModel>
@{
    ViewData["Title"] = "История изменений элементов дерева";
}

<div class="container">
    <hr>
    Фильтры:
    <div id="filter">
        <span class="col-sm-2">Наименование:</span><input id="filter_name" class="col-sm-4" />
        <a href="#" id="refresh_filter_button" class="btn btn-dark col-sm-2 offset-1">Показать</a>
    </div>
    <div id="content"></div>
    <div>
        <a href="#" id="begin"><<</a>
        <a href="#" id="back"><</a>
        Страница <span id="page">0</span> из <span id="all_pages">0</span>
        <a href="#" id="forward">></a>
        <a href="#" id="end">>></a>
        Показывать по <input id="count_items" value="10" /> элементов на странице
    </div>
</div>

@section scripts
{
    <script type="text/javascript">
        var page = 1;
        var name = "";
        var allPages = 1;

        function refresh() {

            $('#page').html(page);
            $.get("Tree/TreeItemHistoryFiltered/?page=" + (page - 1) + "&size=" + $('#count_items').val() + "&name=" + $('#filter_name').val(), function (data, textStatus, request) {
                $('#content').html(data);
                allPages = request.getResponseHeader('x-pages');
                $('#all_pages').html(allPages);
            });
        }

        $(function () {
            $.ajaxSetup({ cache: false });
            refresh();
            $("#refresh_filter_button").click(function () {
                refresh();
            });
            $('#count_items').change(function () {
                refresh();
            });
            $("#begin").click(function () {
                if (page > 1) {
                    page = 1;
                    refresh();
                }
            });
            $("#back").click(function () {
                if (page > 1) {
                    page = page - 1;
                    refresh();
                }
            });
            $("#forward").click(function () {
                if (page < allPages) {
                    page = page + 1;
                    refresh();
                }
            });
            $("#end").click(function () {
                if (page < allPages) {
                    page = allPages;
                    refresh();
                }
            });
        })
    </script>
}

App/ProjectBranchSelector/Views/TreeItem/Index.cshtml
@model IEnumerable<ProjectBranchSelector.Models.TreeItemModel>

@{
    ViewData["Title"] = "List";
}

<h1>List</h1>

<p>
    @Html.ActionLink("Добавить", "Create", 
        new { },
        new { @class = "btn btn-dark", @id = "formula_select" })
    <a href='javascript:history.go(-1)'>Вернуться</a>
</p>

@foreach (var item in Model.Where(s => s.ParentId == null))
{
<li style="margin-top:4px;padding:0px;">
    @Html.HiddenFor(m => item.Id)
    @Html.LabelFor(m => item.Name, item.Name)
    @Html.LabelFor(m => item.Description, item.Description)
    @Html.ActionLink("Add", "Create",
        new { parentId = item.Id },
        new { @class = "btn btn-dark" })
    @Html.ActionLink("Edit", "Edit",
        new { parentId = item.Id },
        new { @class = "btn btn-dark" })
    @Html.ActionLink("Delete", "Delete",
        new { parentId = item.Id },
        new { @class = "btn btn-dark" })
    <ul>
        @Component.InvokeAsync("SelectCategories", new
        {
           list = Model,
           parent = item.Id
       })
    </ul>
</li>
}

App/ProjectBranchSelector/Views/TreeItem/ListSelect.cshtml
@model IEnumerable<ProjectBranchSelector.Models.TreeItemModel>

@{
    ViewData["Title"] = "Выбор элемента";
}

<h1>ViewData["Title"]</h1>

@foreach (var item in Model.Where(s => s.ParentId == null))
{
<li style="margin-top:4px;padding:0px;">
    @Html.HiddenFor(m => item.Id)
    @Html.LabelFor(m => item.Name, item.Name)
    @Html.LabelFor(m => item.Description, item.Description)
    <button class="btn btn-dark select_item" onclick="SetTreeItem(item.Id, item.Name); $('#modDialog').modal('hide');">Выбрать</button>

    <ul>
        @Component.InvokeAsync("SelectCategories", new
        {
           list = Model,
           parent = item.Id
       })
    </ul>
</li>
}

<button class="btn btn-dark select_item" onclick="$('#modDialog').modal('hide');">Отмена</button>

App/ProjectBranchSelector/Views/TreeItem/TreeItemHistoryFiltered.cshtml
@using ProjectBranchSelector.Models;
@model IEnumerable<TreeItemHistoryModel>

<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(s => s.HId)</th>
            <th>@Html.DisplayNameFor(s => s.Id)</th>
            <th>@Html.DisplayNameFor(s => s.Name)</th>
            <th>@Html.DisplayNameFor(s => s.Description)</th>
            <th>@Html.DisplayNameFor(s => s.AddFields)</th>
            <th>@Html.DisplayNameFor(s => s.IsLeaf)</th>
            <th>@Html.DisplayNameFor(s => s.SelectCount)</th>
            <th>@Html.DisplayNameFor(s => s.Weight)</th>
            <th>@Html.DisplayNameFor(s => s.ChangeDate)</th>
            <th>@Html.DisplayNameFor(s => s.IsDeleted)</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@item.HId</td>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td>@item.Description</td>
            <td>@item.AddFields</td>
            <td>@item.IsLeaf</td>
            <td>@item.SelectCount</td>
            <td>@item.Weight</td>
            <td>@item.ChangeDate</td>
            <td>@item.IsDeleted</td>
        </tr>
        }
    </tbody>
</table>